import pkg from 'inquirer';
import { writeFile } from 'fs';
import { promisify } from 'util';

const { prompt } = pkg;
const writeFileAsync = promisify(writeFile);

// Array of questions for user to asnwer to fill the README
const promptUser = () => {
    return prompt([
        {
            type: 'input',
            name: 'github',
            message: 'Enter your GitHub username:',
        },
        {
            type: 'input',
            name: 'githubProfileURL',
            message: 'Provide your GitHub profile URL:',
        },
        {
            type: 'input',
            name: 'projectName',
            message: 'Enter your GitHub repository name (for which you are creating a README):',
        },
        {
            type: 'input',
            name: 'projectSummary',
            message: 'Enter a summary describing your project:',
        },
        {
            type: 'input',
            name: 'demoURL',
            message: 'Enter the assets URL for the screenshot of your project demonstrating how it works:',
        },
        {
            type: 'input',
            name: 'installationInstructions',
            message: 'Describe the installation process:',
        },
        {
            type: 'input',
            name: 'usageInstructions',
            message: 'Describe how to use the project application:',
        },
        {
            type: 'input',
            name: 'testInstructions',
            message: 'Provide testing instructions:',
        },
        {
            type: 'input',
            name: 'contributionGuidelines',
            message: 'Provide contribution guidelines:',
        },
        {
            type: 'input',
            name: 'languages',
            message: 'Enter the languages and libraries used in this project (separated by commas):',
        },
        {
            type: 'list',
            name: 'license',
            message: 'Enter the license for your project:',
            choices: ["Apache", "GNU","MIT","Mozilla", "Eclipse", "Other"]
        },
        {
            type: 'input',
            name: 'contactInfo',
            message: 'Enter your email address for any questions about your project:',
        },
    ]);
};
// Template to answers and fill the README file
function generateMarkdown(answers) {
    return `![GitHub last commit](https://img.shields.io/github/last-commit/${answers.github}/${answers.projectName})  
    ![GitHub code size in bytes](https://img.shields.io/github/languages/code-size/${answers.github}/${answers.projectName})  
    ![GitHub watchers](https://img.shields.io/github/watchers/${answers.github}/${answers.projectName}?label=Watch&style=social)  
    ![GitHub top language](https://img.shields.io/github/languages/top/${answers.github}/${answers.projectName})  
    ![GitHub license](https://img.shields.io/badge/license-${answers.license}-blueyellow) <br> 

# ${answers.projectName}
    
## Table of Contents 
1. [About the Project](#About-The-Project)
1. [Project Links](#Project-Links)
1. [Demo](#Demo)
1. [Getting Started](#Getting-Started)
1. [Installation](#Installation)
1. [Usage](#Usage)
1. [Tests](#Tests)
1. [Contribution Guidelines](#Contribution-Guidelines)
1. [Project Team](#Project-Team)
1. [Questions](#Questions)
1. [License](#License)
    
## About The Project
${answers.projectSummary}
    
## Project Links
[Repo Link](https://github.com/${answers.github}/${answers.projectName}) <br>
[GitHub Project Link](https://${answers.github}.github.io/${answers.projectName}/)
    
## Demo
    
##### This is a screenshot of the application and how it works: <br>
    
![Project Preview](${answers.demoURL}) 
    
## Getting Started
    
#### Languages and libraries used in this project (separate with commas):
${answers.languages}
    
#### Installation: 
\`\`\`  
${answers.installationInstructions}
\`\`\`

#### Usage:
\`\`\`  
${answers.usageInstructions}
\`\`\`

#### Tests:
\`\`\`  
${answers.testInstructions}
\`\`\`

#### Contribution Guidelines:
\`\`\`  
${answers.contributionGuidelines}
\`\`\`
    
## Project Team
[${answers.github}](${answers.githubProfileURL}) <br>

## Questions
<details>
    <summary>Contact</summary>
    ${answers.contactInfo}
</details>
    
## License
#### Distributed under the ${answers.license} License. See [Choose A License](https://choosealicense.com/) for more details.

##### This README was generated by [Professional README Generator](https://github.com/SepidehAyani/professional-README-generator).`;
}

// Using async/await to for final writeFile
const init = async () => {
    console.log('Starting to create requested README file.');
    try {
        const answers = await promptUser();

        const finalFile = generateMarkdown(answers);
        if (answers.license === "Other") {
            console.log("You picked 'Other' for your project license. Please add a license once your file is generated.");
        }
        // function to write README file
        await writeFileAsync('myREADME.md', finalFile);

        console.log('Your README has successfully been created. Please find README.md in the project directory.');
    } catch (err) {
        console.log('An error has occurred. Please try again.' , err);
    }
};
// Function call to initialize program
init();